### ISSUE TITLE
Critical: Confirming Task Cancellation fails for 2.2.0

### ISSUE THREAD

**Issue by mmichaelis** [translations-com/globallink-connect-cloud-api-java#3]
Version 2.2.0 of gcc-restclient fails to confirm task cancellation:

```
org.w3c.dom.DOMException: Error parsing response. Unrecognized field "isJoi" (class org.gs4tr.gcc.restclient.operation.TasksConfirmCancellation$TasksConfirmCancellationResponseData),
not marked as ignorable (one known property: "is_success"])
 at [Source: (String)"{"status":400,"message":"child \"task_ids\" fails because [\"task_ids\" is required]","response_data":{"isJoi":true,"name":"ValidationError","details":[{"message":"\"task_ids\" is required","path":"task_ids","type":"any.required","context":{"key":"task_ids"}}],"_object":{"task_id":1547644651328}}}"; line: 1, column: 116] (through reference chain: org.gs4tr.gcc.restclient.operation.TasksConfirmCancellation$TasksConfirmCancellationResponse["response_data"]->org.gs4tr.gcc.restclient.operation.TasksConfirmCancellation$TasksConfirmCancellationResponseData["isJoi"])
	at org.gs4tr.gcc.restclient.util.APIUtils.doRequest(APIUtils.java:219)
	at org.gs4tr.gcc.restclient.GCExchange.confirmTaskCancellation(GCExchange.java:438)
```

This is because the implementation of 2.2.0 uses a `TaskRequest` (property: `task_id`) rather than a `TasksRequest` (property: `task_ids`).

As this is already fixed in the sources it would be helpful to have a release soon.

**Comment by SergeiTsybulko** [comment]
This is already fixed in 2.2.1-SNAPSHOT
Thank you
