### ISSUE TITLE
GCExchange#getContentList throws DOMException: Error parsing response

### ISSUE THREAD

**Issue by ahubold** [translations-com/globallink-connect-cloud-api-java#5]
We're using version 2.2.1, are connected with https://connect-dev.translations.com/api/v2 and call

```
org.gs4tr.gcc.restclient.GCExchange gcExchange = ...
gcExchange.getContentList(new PageableRequest(1L, count));
```

It throws

```
org.w3c.dom.DOMException: Error parsing response. Unrecognized field "__v" (class org.gs4tr.gcc.restclient.model.GCFile), not marked as ignorable (21 known properties: "content_id", "public_preview_url", "path", "is_translatable", "sequence_number", "file_path", "submitter", "created_at", "name", "node_metadata", "created_by", "target_context_url", "status", "connector_instance_id", "updated_at", "_id", "updated_by", "file_type", "context_url", "pd_classifier", "unique_identifier"])
 at [Source: (StringReader); line: 1, column: 61129] (through reference chain: org.gs4tr.gcc.restclient.operation.Content$ContentResponse["response_data"]->org.gs4tr.gcc.restclient.operation.Content$ContentResponseData["content_list"]->java.util.ArrayList[112]->org.gs4tr.gcc.restclient.model.GCFile["__v"])

	at org.gs4tr.gcc.restclient.util.APIUtils.doRequest(APIUtils.java:219)
	at org.gs4tr.gcc.restclient.GCExchange.getContentList(GCExchange.java:199)
```

Seems like the REST client does not understand the response from the server.

**Comment by SergeiTsybulko** [comment]
Error happened because of api update on server. Resolved
